name: single_radio
description: Single channel radio player.
publish_to: 'none'
version: 2.0.1+29

environment:
  sdk: '>=3.2.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 2.22.0
  firebase_messaging: 14.7.4
  flutter_local_notifications: 16.1.0
  #google_mobile_ads: 3.0.0
  provider: 6.1.1
  http: 1.1.0
  share_plus: 7.2.1
  in_app_review: 2.0.8
  flutter_markdown: 0.6.18+2
  flutter_svg: 2.0.9
  url_launcher: 6.2.1
  text_scroll: 0.2.0
  sleek_circular_slider : 2.0.1
  radio_player: 1.5.0
  volume_regulator: 2.2.0
  dart_common_utils: 1.0.0
  android_minimizer: 0.0.1

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_launcher_icons: 0.13.1
  flutter_native_splash: 2.3.2
  change_app_package_name: 1.1.0

flutter_icons:
  image_path: "assets/appicon/appicon.png"
  adaptive_icon_background: "#FF131313"
  adaptive_icon_foreground: "assets/appicon/appicon-adaptive.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#151f2c"
  image: assets/splash/splash.png
  android: true
  ios: true

  android_12:
    color: "#151f2c"
    color_dark: "#151f2c"
    image: assets/splash/splash12.png
    image_dark: assets/splash/splash12.png

flutter:
  uses-material-design: true
  assets: 
    - assets/text/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Custom
      fonts:
        - asset: fonts/Light.ttf
          weight: 300
        - asset: fonts/Regular.ttf
          weight: 400
        - asset: fonts/Medium.ttf
          weight: 500
        - asset: fonts/SemiBold.ttf
          weight: 600
        - asset: fonts/Bold.ttf
          weight: 700
        - asset: fonts/ExtraBold.ttf
          weight: 800
